### ISSUE TITLE
Copy function doesn't work as intended

### ISSUE THREAD

**Issue by soumeh01** [ARM-software/golang-utils#195]
**Describe the bug**
`Copy `method in the filesystem is intended to behave like `cp -r`. 

1. It should copy the content from the source path recursively (when the destination directory doesn't exist) and place it under the destination path. Instead, it copies the source directory itself and places it under the destination path.

**Expected behavior**

1. Destination directory not available
    - Create a destination directory
    - Copy the content of the source directory into the destination directory recursively

2. Destination directory is available
    - Copy the source directory into the destination directory

**Desktop (please complete the following information):**
 - OS: [win10]

**Comment by acabarbaye** [comment]
Release 1.25.1 contains a fix for this issue
